apiVersion: v1
kind: Service
metadata:
  name: bedrock-server
  labels:
    app: minecraft
spec:
  externalIPs:
  - 192.168.0.114
  ports:
  - name: bedrock
    port: 19132
    protocol: UDP
    targetPort: 19132
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bedrock-server-deployment
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: bedrock-server
        image: 192.168.0.114:30500/minecraft/bedrock_server:1.9.0.15
        volumeMounts:
          - name: nfs-bedrock-server
            mountPath: /home/bedrock/bedrock_server/worlds
            subPath: worlds
          - name: nfs-bedrock-server
            mountPath: /home/bedrock/bedrock_server/server.properties
            subPath: server.properties
      volumes:
      - name: nfs-bedrock-server
        persistentVolumeClaim:
          claimName: nfs-bedrock-server
