apiVersion: v1
kind: Pod
metadata:
  name: bedrock-server
spec:
  containers:
  - name: bedrock-server
    image: 192.168.0.114:30500/minecraft/bedrock_server:1.9.0.15
    #    volumeMounts:
    #      - name: nfs-pvc
    #        mountPath: "/mnt"
  restartPolicy: "Never"
  #  volumes:
  #    - name: nfs-pvc
  #      persistentVolumeClaim:
  #        claimName: task-pv-claim
